<?php
include "../includes/database.php";
require '../simple_html_dom.php';
session_start();
global $conn;
$peliId = $_POST['pelicula'];
$bibliotecaId = $_POST['biblioteca'];
$sql = "SELECT * FROM originals WHERE pelicode = ".$peliId."";
        $result = $conn->query($sql);
        $html = '<div class="modal-contenido"><div class="modal-titulo">Edita los datos</div>';
        $html .= '<a onclick="goback(2)" class="modal-back">Atràs</a>';
    	$html .= '<a onclick="closeModal()" class="modal-close">x</a>';
        $html .= '<form class="searchFilm" id="editNewFilm" method="POST">';
      	while($row = $result->fetch_assoc()) {
      		$html .= '<div class="col-md-12">';
      		$html .= '<div class="col-md-6">';
      		$html .= '<div class="input-label">Nombre</div>';
			$html .= '<input type="text" name="pelinom" value="'.$row["pelinom"].'">';
			$html .= '</div>';
			$html .= '<div class="col-md-6">';
			$html .= '<div class="input-label">Nombre original</div>';
			$html .= '<input type="text" name="pelioriginal" value="'.$row["pelioriginal"].'">';
			$html .= '</div>';
			$html .= '</div>';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="col-md-2">';
			$html .= '<div class="input-label">Duración</div>';
			$html .= '<input type="text" name="peliduracio" value="'.$row["peliduracio"].'">';
			$html .= '</div>';
			$html .= '<div class="col-md-2">';
			$html .= '<div class="input-label">Año</div>';
			$html .= '<input type="text" name="peliano" value="'.$row["peliano"].'">';
			$html .= '</div>';
			$html .= '<div class="col-md-2">';
			$html .= '<div class="input-label">Valoración</div>';
			$html .= '<input type="text" name="pelivaloracion" value="">';
			$html .= '</div>';
			$html .= '<div class="col-md-6">';
			$html .= '<div class="input-label">Página web</div>';
			$html .= '<input type="text" name="peliweb" value="'.$row["peliweb"].'">';
			$html .= '</div>';
			$html .= '</div>';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="col-md-6">';
			$html .= '<div class="input-label">Director</div>';
			$html .= '<input type="text" name="pelidirector" value="'.$row["pelidirector"].'">';
			$html .= '</div>';
			$html .= '<div class="col-md-6">';
			$html .= '<div class="input-label">País</div>';
			$html .= '<input type="text" name="pelipais" value="'.$row["pelipais"].'">';
			$html .= '</div>';
			$html .= '</div>';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="input-label">Género</div>';
			$html .= '<input type="text" name="peligenero" value="'.$row["peligenero"].'">';
			$html .= '</div>';
			$html .= '</div>';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="input-label">Guió</div>';
			$html .= '<input type="text" name="peliguio" value="'.$row["peliguio"].'">';
			$html .= '</div>';
			$html .= '</div>';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="input-label">Productora</div>';
			$html .= '<input type="text" name="peliproductora" value="'.$row["peliproductora"].'">';
			$html .= '</div>';
			$html .= '</div>';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="input-label">Música</div>';
			$html .= '<input type="text" name="pelimusica" value="'.$row["pelimusica"].'">';
			$html .= '</div>';
			$html .= '</div>';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="input-label">Imagen</div>';
			$html .= '<input type="text" name="peliimatge" value="'.$row["peliimatge"].'">';
			$html .= '</div>';
			$html .= '</div>';
			$html .= '<div class="col-md-12">';
			$html .= '<div class="col-md-6">';
			$html .= '<div class="input-label">Reparto</div>';
			$html .= '<textarea class="areamodal" name="pelireparto">'.$row["pelireparto"].'</textarea>'; 
			$html .= '</div>';
			$html .= '<div class="col-md-6">';
			$html .= '<div class="input-label">Sinópsis</div>';
			$html .= '<textarea class="areamodal" name="peliresumen">'.$row["peliresumen"].'</textarea>';
			$html .= '</div>';
			$html .= '</div>';
			$html .= '<input type="hidden" name="pelicode" value="'.$row["pelicode"].'">';
			$html .= '<input type="hidden" name="usuario" value="'.$_SESSION["id_usuario"].'">';
			$html .= '<input type="hidden" name="biblioteca" value="'.$bibliotecaId.'">';
		}
		$html .= '<a onclick="saveFilm()" class="btn btn-success">Añadir</button>';
		$html .= '</form></div>';

		echo $html;